### ISSUE TITLE
AlwaysOn  vs Doze Mode

### ISSUE THREAD

**Issue by kavidriod** [googlesamples/android-AlwaysOn#1]
Hi,
  In this app,if device enters in to doze mode,Still Application will run with out stopping timer?

**Comment by codingjeremy** [comment]
This app **only** tracks updates in refresh time while it is active meaning it should be in the Active bucket ([details](https://developer.android.com/about/versions/pie/power)). If you navigate away from it, it stops running timers/alarms.

If the device goes into doze mode, it still should work since the app was active. If not, you might want to check out [this link](https://stackoverflow.com/questions/32492770/how-to-make-alarm-manager-work-when-android-6-0-in-doze-mode). Otherwise, please reopen this issue in our new repo for Wear OS samples (below). This samples ha been moved there: [github.com/android/wear-os](https://github.com/android/wear-os).
